cloud_sources:
  - name: /cloud_selffiltered_old
    frame_subsample: 1
    point_subsample: 1
    sensor_frame: /openni_rgb_optical_frame
    dynamic_publish: true
    static_publish: true
    dynamic_until_static_publish: true
    dynamic_buffer_size: 25
