## This file should be loaded under <robot description>_planning

## the definition of each group
groups:
  - name: irp6p
    joints:
      joint1
      joint2
      joint3
      joint4
      joint5
      joint6
    links:
      base_link
      link1
      link2
      link3
      link4
      link5
      link6
      griper_link
