min_sensor_dist: .05
self_see_default_padding: .02
self_see_default_scale: 1.0
self_see_links:
  - name: link1
    padding: .2
  - name: link2
    padding: .2
  - name: link3
    padding: .05
  - name: link4
    padding: .2
  - name: link5
    padding: .2
  - name: link6
    padding: .1
  - name: base_link
    padding: .02
  - name: griper_link
    padding: .05
