joint_limits:
  lwr_arm_0_joint:
    has_position_limits: true
    min_position: -2.96705973
    max_position: 2.96705973
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  lwr_arm_1_joint:
    has_position_limits: true
    min_position: -2.0943951
    max_position: 2.0943951
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  lwr_arm_2_joint:
    has_position_limits: true
    min_position: -2.96705973
    max_position: 2.96705973
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  lwr_arm_3_joint:
    has_position_limits: true
    min_position: -2.0943951
    max_position: 2.0943951
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  lwr_arm_4_joint:
    has_position_limits: true
    min_position: -2.96705973
    max_position: 2.96705973
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  lwr_arm_5_joint:
    has_position_limits: true
    min_position: -2.0943951
    max_position: 2.0943951
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5